### ISSUE TITLE
tvOS Support

### ISSUE THREAD

**Issue by JALsnipe** [FLEXTool/FLEX#197]
I've started looking into tvOS support, but we would have to re-write a lot of the UI as well as conditionally change things like UIStatusBar and UIAlertView usage.  Has anyone else started digging into this?

**Comment by NSExceptional** [comment]
How would this work on a device where you can't tap views?

**Comment by DylanDuff** [comment]
Are there any chances of this coming to fruition ?

**Comment by NSExceptional** [comment]
Unlikely unless someone volunteers out of the goodness of their heart

—
Tanner Bennett

**Comment by NSExceptional** [comment]
Closing because @JALsnipe has not responded in over a year. I can reopen this if someone shows interest in helping make this happen.

**Comment by lechium** [comment]
@NSExceptional im open to helping make this a reality on tvOS. however, im unfamiliar with the code base so i need some direction on where to start. also having an issue wrapping my head around the different UX paradigm. (siri remote and focus engine v tappable UI)

thats a tricky one to solve.

**Comment by NSExceptional** [comment]
Yeah, I'm not sure it makes a ton of sense to have a Select button since you can't tap on things. Maybe it would be better to disable it entirely.

I'm also not sure how a floating FLEX bar would work. How do you move it? How do you move the cursor between the bar and the app? Etc

**Comment by lechium** [comment]
actually it works quite well after heavily macroing / stubbing things out. select should be disabled for sure but i think i should have a good enough initial version by end of the day with most if the rest working. [sample video](https://www.dropbox.com/s/xn18z1a6a8axq1w/IMG_0018.mov?dl=1)

**Comment by lechium** [comment]
@NSExceptional in addition i have an idea for what select could be: a search menu, theres no concept of search controllers in tvOS as they exist used here. that being said select mode does partially have a place because the siri remote "just works" when moving view elements.

**Comment by lechium** [comment]
i think its safe to re-open this issue: if anyone wants to follow along w/ my progress on my fork: https://github.com/lechium/FLEX

**Comment by lechium** [comment]
@NSExceptional @DylanDuff @JALsnipe initial stable tvOS release available: https://github.com/lechium/FLEX/releases/tag/4.1.1-tvOS

the code is a bit of a #if TARGET_OS_TV mess right now so im not quite ready to do a MR but aside from searching and snapshotting this has pretty much every other possible feature / view covered.

**Comment by NSExceptional** [comment]
I can see you're still actively working on this. Do you want to convert it to a draft PR instead until you're done?

**Comment by NSExceptional** [comment]
I like to keep a linear commit history on the repo if we can. Do you know how to use git rebase? If not, once you get a PR ready I will need to organize the commits and get rid of that merge

**Comment by lechium** [comment]
get rid of which merge? @NSExceptional not sure what you mean. im pretty familiar with rebasing, although ive never done it across forks. just different branches.

**Comment by NSExceptional** [comment]
This merge in the middle:

![image](https://user-images.githubusercontent.com/8371943/103488158-3ba9ad00-4dbf-11eb-99a3-0285ab61d728.jpeg)

**Comment by lechium** [comment]
@NSExceptional ahh okay that one. ill see if i can figure it out.

**Comment by lechium** [comment]
@NSExceptional okay i closed my original MR and created a fresh new one from a different branch. https://github.com/FLEXTool/FLEX/pull/500
its not perfect yet but its definitely mostly full featured, very stable and very usable.

**Comment by NSExceptional** [comment]
Forgot to close this, but anyone looking for tvOS support should use @lechium's fork. I will be adding it to the readme.

**Comment by lechium** [comment]
@NSExceptional no problem, i would definitely like to help with the refactor in any way i can if & when you get to one to make it easier to support other platforms like tvOS. please give me a heads up when you do!
