### ISSUE TITLE
FLEXNetworkObserver crashes when used with AVAssetDownloadTask or AVAggregateAssetDownloadTask

### ISSUE THREAD

**Issue by adysart** [FLEXTool/FLEX#276]
If you use a `AVAssetDownloadURLSession` for downloading video assets, this will still be used with the network logging facility in FLEX. However, the tasks used for this `NSURLSession` subclass as instances of `AVAssetDownloadTask` or `AVAggregateAssetDownloadTask`. Both of these classes declare that the properties `originalRequest`, `currentRequest` and `response` are unavailable. However this line in `FLEXNetworkObserver`:

https://github.com/Flipboard/FLEX/blob/master/Classes/Network/PonyDebugger/FLEXNetworkObserver.m#L1115

attempts to access those properties (when network logging in enabled) and thus crashes with this exception:

> *** Terminating app due to uncaught exception 'NSGenericException', reason: 'AVAggregateAssetDownloadTask does not support currentRequest property'

I'm not sure what would be the solution here. Perhaps don't use network logging with instances of `AVAssetDownloadURLSession`?

**Comment by NSExceptional** [comment]
Looks like there's an `originalRequest` property, maybe we could do some swizzling and make `AVAggregateAssetDownloadTask.currentRequest` call into `originalRequest`?

I like to avoid throwing exceptions even if we're going to catch them, because the alternative is to wrap the whole thing in a `@try-@catch` and use `originalRequest` instead of we catch an exception. That's just me though

**Comment by NSExceptional** [comment]
Could you try that for me and see if it works actually? Should be as simple as adding this code somewhere in your project:

```objc
@interface AVAggregateAssetDownloadTask (Fix)
@end

@implementation AVAggregateAssetDownloadTask (Fix)
- (id)currentRequest { return self.originalRequest; }
@end
```

**Comment by adysart** [comment]
`originalRequest` is _also_ marked as `NS_UNAVAILABLE` so I assume that it will also assert. From AVAssetDownloadTask.h:
```
// NSURLRequest and NSURLResponse objects are not available for AVAssetDownloadTask
AV_INIT_UNAVAILABLE
@property (readonly, copy) NSURLRequest *originalRequest NS_UNAVAILABLE;
@property (readonly, copy) NSURLRequest *currentRequest NS_UNAVAILABLE;
@property (readonly, copy) NSURLResponse *response NS_UNAVAILABLE;
```
From what I can tell Apple _really_ doesn't want to expose the inner workings of `AVAssetDownloadURLSession`.

**Comment by NSExceptional** [comment]
Hmmm, yeah I guess we just gotta disable it for those tasks. There doesn't seem to be any obvious place the requests would be stored.

**Comment by rahulnainwal107** [comment]
How to solve this issue? Any ways to get rid of it?
