### ISSUE TITLE
CONTRIBUTING.md - Lacking Information

### ISSUE THREAD

**Issue by patrickdicks** [FLEXTool/FLEX#284]
The CONTRIBUTING.md simply contains one line stating "We welcome contributions! Please open a pull request with your changes." 

This feels underwhelming and is not very welcoming to first-time contributors. Many may not even understand what a pull request is, let alone how to open one. This lack of detail is a major turn off for some and does not do a good job of encouraging new contributions.

I feel like the minimum information contained in a CONTRIBUTING.md should be:
1. Identifying Project Issues
2. How to perform a Pull Request and what that actually means.
3. How to Merge a Pull Request
4. How to contact others involved with the project

Although much of this information may seem unnecessary, it would be extremely helpful in creating a sense of welcomeness to new GitHub users and giving them a starting point for understanding how to contribute.

**Comment by NSExceptional** [comment]
You make some good points! Can you point me to an example of a well-thought-out CONTRIBUTING.md that I might copy from?

As for contacting those involved with the project, the best way to do that is to simply open an issue. I will be sure to mention that in the new doc.

**Comment by NSExceptional** [comment]
Might be good to have a small section on coding conventions addressing stuff like this:

```objc
// yes
- (void)foo:(id)f bar:(void *)bar
{
    if (condition) {
        ...
    }
}

// nooo
-(void)foo: (id)f bar:(void*) bar{
    if(condition){
        ...
    }
}
```
