### ISSUE TITLE
WKWebView requests not appearing in Network History

### ISSUE THREAD

**Issue by Args** [FLEXTool/FLEX#293]
Any plans？

**Comment by NSExceptional** [comment]
I'm not sure what you mean, can you elaborate?

**Comment by Args** [comment]
I mean, when a web request occurs in a wkwebview, there is no record in the request record list

**Comment by NSExceptional** [comment]
It does for me. Are you confusing WKWebView with SFSafariViewController?

**Comment by Args** [comment]
Wow,it's indeed a WKWebView.
I can't see any network requests in the `Network History`,and the `Network Debugging` in settings is on.
I jsut called the method `[[FLEXManager sharedManager] showExplorer];` in the Appdelegate.
So..Is anything missing？

**Comment by NSExceptional** [comment]
Is this project on GitHub? If not can you upload it for me to look at?

**Comment by Args** [comment]
I compared the differences and it does for me too after I added `[[FLEXManager sharedManager] setNetworkDebuggingEnabled:YES];`
But I turned on debugging enable in the interface and it still didn't work?
Anyway, it doesn't matter, thank you!

**Comment by Args** [comment]
Emmm, here I go again. I found that if my wkwebview was written in swift it wouldn't work, but objc is ok

**Comment by NSExceptional** [comment]
Can you upload a sample project for me to debug?

**Comment by Args** [comment]
Here's my [code](https://github.com/Args/FLEXSample)

**Comment by NSExceptional** [comment]
Hmmm, interesting. I don't know how we never noticed this before. Thanks for reaching out, I'll look into this when I have time—nothing obvious stands out to me currently.

I have uploaded a version of the project which uses Cocoapods instead of Carthage for those who don't have carthage installed (or can't install it, like on 10.15 beta)

[FLEX-WKWebView-bug.zip](https://github.com/Flipboard/FLEX/files/3503578/FLEX-WKWebView-bug.zip)

**Comment by NSExceptional** [comment]
Update for my future self: still an issue as of FLEX 4.1.

**Comment by NSExceptional** [comment]
Updating with a list of functions we would probably need to hook, since it appears `WKWebView` passes `NSURLRequest` objects to WebKit directly:

- [ ] `WebKit::WebPageProxy::loadFile`
- [ ] `WebKit::WebPageProxy::loadRequest`
- [ ] `WebKit::WebPageProxy::loadData`

**Comment by yFeii** [comment]
I tried hook these APIs  by fishhook, but the symbol is <redacted>  when running on the iOS really device...

**Comment by NSExceptional** [comment]
Can you share your code?

**Comment by yFeii** [comment]
```javascript


void _enumerate_segment(const mach_header *header, std::function<bool(struct load_command *)> func) {
    struct load_command *baseCommand = (struct load_command *)((struct mach_header_64 *)header + 1);
    if (baseCommand == nullptr) return;
    
    struct load_command *command = baseCommand;
    for (int i = 0; i < header->ncmds; i++) {
        if (func(command)) {
            return;
        }
        command = (struct load_command *)((uintptr_t)command + command->cmdsize);
    }
}


char * _demangle_symbol(char* mangle_symbol) {
    size_t str_len = strlen(mangle_symbol);
    if (str_len < 3) {
        return mangle_symbol;
    }
    
    if (PLATFORM_IOS) {
        if (strstr(mangle_symbol, "__Z") == mangle_symbol) {
            char *new_mangle_symbol = mangle_symbol + 1;
            int status;
            char *demangle_symbol = abi::__cxa_demangle (new_mangle_symbol, nullptr, 0, &status);
            return status == 0 ? demangle_symbol : mangle_symbol;
        }
    } else  {
        int status;
        char *demangle_symbol = abi::__cxa_demangle (mangle_symbol, nullptr, 0, &status);
        return status == 0 ? demangle_symbol : mangle_symbol;
    }
   
    return mangle_symbol;
}
/*
 call this method for get all symbol of `WebKit.framework`.
then use the symbol to hook some method by fishhook.
*/
void log_dyld_all_symbol(char const*dyld_name) {

    const struct mach_header *header = NULL;
    uint64_t slide;

    int count = _dyld_image_count();
    for (int i = 0; i < count; i++) {
        const char* name = _dyld_get_image_name(i);
        if(strstr(name, dyld_name) > (char *)0) {
            header = _dyld_get_image_header(i);
            slide = _dyld_get_image_vmaddr_slide(i);
            break;
        }
    }
    
    segment_command_64 *seg_linkedit = NULL;
    segment_command_64 *seg_text = NULL;
    struct symtab_command *symtab_command = NULL;

    _enumerate_segment(header, [&](struct load_command *command) {
        if (command->cmd == LC_SEGMENT_64) {
            struct segment_command_64 *segCmd = (struct segment_command_64 *)command;
            if (0 == strcmp((segCmd)->segname, SEG_LINKEDIT))
                seg_linkedit = segCmd;
            else if (0 == strcmp((segCmd)->segname, SEG_TEXT))
                seg_text = segCmd;
        } else if (command->cmd == LC_SYMTAB) {
            symtab_command =  (struct symtab_command *)command;
        }
        return false;
    });
    
    uintptr_t linkedit_addr = (uintptr_t)seg_linkedit->vmaddr -(uintptr_t)seg_text->vmaddr - (uintptr_t)seg_linkedit->fileoff;
    struct nlist_64 *nlist = (struct nlist_64 *)((uintptr_t)header + (uintptr_t)symtab_command->symoff + linkedit_addr);
    intptr_t string_table = (intptr_t)header + ((uintptr_t)symtab_command->stroff + (uintptr_t)linkedit_addr);
    for (int i = 0; i < symtab_command->nsyms ; i++) {
        char * symbol_name = (char *)(string_table + nlist->n_un.n_strx);
        char * demangle_symbol = _demangle_symbol(symbol_name);
        printf("symbol_name: %s\n", symbol_name);
        printf("demangle_symbol: %s\n", demangle_symbol);
        nlist = (struct nlist_64 *)((uintptr_t)nlist + sizeof(struct nlist_64));
    }
    
}

```
log at simulator 
![image](https://user-images.githubusercontent.com/24515770/83723352-232eb400-a671-11ea-9b5d-237e40d69023.png)

at ios device

![image](https://user-images.githubusercontent.com/24515770/83723536-743ea800-a671-11ea-846a-d47625cb2ab2.png)

**Comment by sbingner** [comment]
IDK where you get that `<redacted>` stuff from but if you just use `MSFindSymbol` on the symbol it works fine:

```
iPhone-XS-Max:~ root# findsym /System/Library/Frameworks/WebKit.framework/WebKit __ZN6WebKit12WebPageProxy43didStartLoadForQuickLookDocumentInMainFrameERKN3WTF6StringES4_.cold.1 
calling MSFindSymbol(0x14de02320, __ZN6WebKit12WebPageProxy43didStartLoadForQuickLookDocumentInMainFrameERKN3WTF6StringES4_.cold.1)
0x19c8077e8
```

**Comment by rkittinger** [comment]
After updating to 4.1.1 I still see no network history.
FLEXManager.shared.isNetworkDebuggingEnabled = true is called in appdelegate

**Comment by NSExceptional** [comment]
Closing this in favor of a discussion since this will probably not be resolved anytime soon. Please direct further comments to #495.
