### ISSUE TITLE
Crash when using NSArray subscript with FLEX 4.0

### ISSUE THREAD

**Issue by annguyen011197** [FLEXTool/FLEX#398]
After updated FLEX to version 4.0,  when I use subscript with NSArray application will crash
Ex: ```let code = try array[index] as? String```

Crash log:
> NSInvalidArgumentException:-[__NSSingleObjectArrayI objectForKeyedSubscript:]: unrecognized selector sent to instance 0x280733400

**Comment by jackvt93** [comment]
Same here. Please help us.

**Comment by NSExceptional** [comment]
I don't understand, can you provide more context?

**Comment by NSExceptional** [comment]
Are you still having this problem as of `4.2.0`?

**Comment by NSExceptional** [comment]
@annguyen011197 @jackvt93 If either of you are still experiencing this issue with a newer version of FLEX, please let me know and we can reopen this. I think it was fixed though.
