### ISSUE TITLE
No animation when FLEX automatically scrolls to the selected view

### ISSUE THREAD

**Issue by Ram4096** [FLEXTool/FLEX#405]
1. Invoke the FLEX bar.
2. Tap "Select", and select any view.
3. Tap "Views" and you can see that there is no animation when FLEX automatically scrolls the table.

**Comment by NSExceptional** [comment]
I am unable to reproduce this. Which version of iOS and the library are you using?

**Comment by matrush** [comment]
Close old issues as it's not actionable for now.
