### ISSUE TITLE
Importing FLEX causes Swift code to magically not compile

### ISSUE THREAD

**Issue by davidchristiandy** [FLEXTool/FLEX#409]
As title states, FLEX causes some weird behavior on Obj-C interoperability when Swift tries to mutate NSMutableArray property read from Obj-C source. The full error message is:
```
Cannot assign through subscript: subscript is get-only
```
### Repro Steps
1. Add FLEX to project.
2. Create an Objective-C file with `NSMutableArray` property, e.g.
```objc
@interface Foo
@property (strong, nonatomic) NSMutableArray<NSString *> *strings;
@end
```
3. Use Objective-C class above in Swift, and mutate its property, e.g.
```swift
class TestCase {
  let foo: Foo = Foo()

  func doSomething {
    foo.strings[0] = "Hello, world!" // triggers the error.
  }
}
```
### Expected Output
The code should compile just fine.

### Notes
- Confirmed that without FLEX, the code compiled just fine.
- Tested on FLEX version 4.0.0 and 4.1.1.
- Can be reproduced in Xcode 11.4 and 11.3.1.
- May be related to #398?

### Standalone Project
[Repro.zip](https://github.com/Flipboard/FLEX/files/4442048/Repro.zip)

**Comment by NSExceptional** [comment]
Hi,

I'm still unable to determine whether this is really FLEX's fault or something wrong with the Swift compiler. FLEX doesn't declare any methods or properties named `strings` and frankly I'm not sure how FLEX could break Swift code like this.

I think you should file a bug on bugs.swift.org and send them your example project! I bet someone there will know what's going on. That or you found a bug in the compiler.

I'll leave this open

**Comment by davidchristiandy** [comment]
Hello, and thanks for the reply!

> FLEX doesn't declare any methods or properties named strings and frankly I'm not sure how FLEX could break Swift code like this.

To clarify, the generic type and the variable name can be _anything_ on the Obj-C side. The issue is that somehow, Swift compiler throws error when property of type `NSMutableArray` (defined in Obj-C) is mutated on the Swift side.

> I think you should file a bug on bugs.swift.org and send them your example project!

Sure, I'll try to post there and will post any updates from there if any. 

Thanks!

**Comment by rounak** [comment]
I'm facing the same issue. I think it has to do with the extension on NSArray/NSMutableArray `FLEXCollection`. This declares something that's a subscript but it's get only, so for some reason swift now can't see the get/set subscript.

**Comment by NSExceptional** [comment]
This should be fixed in the next update. I'm going to close this, please reopen it if the issue persists! The current version is 4.1.1, so it will be the next one after that.
