### ISSUE TITLE
Don't make extensions public

### ISSUE THREAD

**Issue by alexito4** [FLEXTool/FLEX#410]
FLEX makes public some extensions to UIKit types that are not apparent at all that come from FLEX. For example: `UIBarButtonItem(image:, target:, action:)`.

Since FLEX should only be used in Debug configurations this creates a situation where somebody mistakenly uses this extensions and the issue is not found until release day when the App is compiled for Release, which strips FLEX and makes that method unavailable.

Is there any good reason to make those methods part of the public API? And if so, should they be prefixed clearly to show from where they come?

**Comment by NSExceptional** [comment]
You raise a good issue, I will prefix these in a future release. They are public so that you can use them to build your own extensions to FLEX if you want.
