### ISSUE TITLE
How to copy or export system log ? 

### ISSUE THREAD

**Issue by zhaozhu-he** [FLEXTool/FLEX#415]
Hi wanna know can we copy or export the system logs ?  So that we can analyze some infos more clearly. 
Thanks.

**Comment by zhaozhu-he** [comment]
looks like in version 3.x I could long press to copy system log, but version 4.x seems not work ?

**Comment by smit9612** [comment]
@here  is there any possibility to add a feature to dump logs in some file

**Comment by NSExceptional** [comment]
I'll work on these 👍🏼

**Comment by 7a** [comment]
It would be great if the system log was saved into a file by default, this way, regardless of app crashes a full trail of logs would exist, which would be very valuable while performing app audits.

Thank you!
