### ISSUE TITLE
About automated testing

### ISSUE THREAD

**Issue by Luswen** [FLEXTool/FLEX#419]
Hello, I have a problem in using flex. What can I do to export the node information of view hierarchy to a local file

The uiautomator on the Android platform can be saved as an XML file containing all the node information, so that it is more convenient for the automatic test of the app

**Comment by NSExceptional** [comment]
At the moment no such functionality is present, but I may add it if you can make a case for why it's useful. What sort of testing do you expect to do with this information?

**Comment by Luswen** [comment]
> At the moment no such functionality is present, but I may add it if you can make a case for why it's useful. What sort of testing do you expect to do with this information?

Thank you very much for your reply, flex is a very powerful and practical tool, I solved a lot of problems with him, but, flex the lack of a flexible way to call, all the current operations I am manually to test, this is acceptable for a small amount of work, but tens of thousands of repetitive and logical operations, plus interface and code iteration, a variety of different ios devices, I can not imagine what will happen On Android, I can easily write my own script for automated testing software bug, but ios, I haven't found a tool until flex Finally, I sincerely hope that you can join this function.

**Comment by NSExceptional** [comment]
I see

Just making sure, but have you looked into UI testing with Xcode? Xcode has automated UI testing built in

**Comment by Luswen** [comment]
> I see
> 
> Just making sure, but have you looked into UI testing with Xcode? Xcode has automated UI testing built in

Yes, I did, but it, but it's only tested on your own software. It's not very friendly, and it's not flex powerful

**Comment by NSExceptional** [comment]
After some thought, adding something like this to FLEX seems like feature creep / out of scope for the project. FLEX is a debugging tool, not meant to assist in testing. It would be simple enough for anyone to write something to traverse the view hierarchy and export the necessary information.
