### ISSUE TITLE
Using the latest version 4.1.1 breaks property accessing on mutable arrays

### ISSUE THREAD

**Issue by revolter** [FLEXTool/FLEX#426]
Having

```objc
NSArray<NSNumber *> *test1 = @[@(1)];
NSInteger test1Integer = test1[0].integerValue;

NSMutableArray<NSNumber *> *test2 = [@[@(1)] mutableCopy];
NSInteger test2Integer = test2[0].integerValue;
```

errors out at the last line with

> Property 'integerValue' not found on object of type 'id'

while the second line works.

I think it's caused by `FLEXCollectionContentSection.h`, but not sure. Do you have any idea?

**Comment by revolter** [comment]
Commenting out

```objc
@interface NSMutableArray (FLEXMutableCollection) <FLEXMutableCollection> @end
```

works.

**Comment by NSExceptional** [comment]
Yeah, that whole thing is causing a slew of problems apparently. I need to fix it.

**Comment by revolter** [comment]
But I don't understand why would a protocol break it this way.

**Comment by NSExceptional** [comment]
The methods declared in the protocol override the ones declared in the class's own interface, losing type information.

**Comment by revolter** [comment]
But I expected for it to generate warnings when declaring the variable, not when using it. What I mean is that

```objc
NSMutableArray<NSNumber *> *test2 = @"test"; // Incompatible pointer types initializing 'NSMutableArray<NSNumber *> *' with an expression of type 'NSString *'
NSInteger test2Integer = test2[0].integerValue;
```

works, because the compiler only looks at how you declared a variable, not at how you initialized it. So lost type information for `mutableCopy` should only trigger a warning when initializing the variable, not a compiler error when using a property on it.
