### ISSUE TITLE
App crash due to [NSProxy methodSignatureForSelector:] called

### ISSUE THREAD

**Issue by yur1xpp** [FLEXTool/FLEX#427]
I gets a lots of crash when scrolling through the FLEX window in Spotify. Whenever it get scrolled to some properties/ivars/methods, it crashed with this crash log: 
https://pastebin.com/1TSewyWY 

This happens most definitely on `SPTFreeTierPlaylistViewController` class in Spotify 8.5.60, with 100% chances of reproducing. You can reproduce this by open any playlist in Spotify, select a row to be inspected, find the `SPTFreeTierPlaylistViewController`, go to its view controller and scroll. It'll crash right after that.

Here's the video of how it happens: 
https://imgur.com/a/riIasd6

Hopefully this bug gets crushed, thanks in advance.

**Comment by NSExceptional** [comment]
Thanks! Fixed in the next release
