### ISSUE TITLE
In FLEX 4.0 it's hard to copy a value from a cell in the database viewer

### ISSUE THREAD

**Issue by matrush** [FLEXTool/FLEX#432]
In FLEX 3.0 tapping on a cell will take you to a view with the cell's text only. So you can copy text from there, or tap on a link to open the it in web browser.
In FLEX 4.0, the behavior after tapping on a cell becomes popping up an alert view with details from all cells of that row, which is sometimes handy, but not always useful, especially for scenarios I mentioned above.

We should try to keep both functionality working. Maybe use tap and long press gesture combinations for simple preview and full row preview cases respectively?

**Comment by NSExceptional** [comment]
I will look into adding a context menu (haptic touch) for this!

**Comment by NSExceptional** [comment]
Correct me if I'm wrong but your PRs to enhance the database viewer resolve this!
