### ISSUE TITLE
In FLEX 4.0 you can't edit NSUserDefaults (Preferences) anymore

### ISSUE THREAD

**Issue by revolter** [FLEXTool/FLEX#433]
Or am I missing something?

<img alt="Simulator Screen Shot - iPhone 11 Pro - 2020-06-26 at 10 59 07" src="https://user-images.githubusercontent.com/5748627/85834459-11d25680-b79c-11ea-9a0c-b45140cd2d0b.png" width="375" height="812">

**Comment by NSExceptional** [comment]
You have always had to use the methods, `set*:forKey:`.

**Comment by revolter** [comment]
You had this with `Get` and `Set` toolbar buttons:

![Simulator Screen Shot - iPhone 11 Pro - 2020-06-29 at 14 07 43](https://user-images.githubusercontent.com/5748627/85997218-ea84bf00-ba11-11ea-8d63-80205c5939c8.png)

**Comment by NSExceptional** [comment]
That is news to me 😳 I'll take a look!

**Comment by revolter** [comment]
As a side note, I'm pretty sure that in even older versions, booleans were showing up as `UISwitch`es. And also, now, opening an integer user default with the value `0` or `1` gets loaded with `false` or `true` in the text view.

**Comment by revolter** [comment]
> You have always had to use the methods, `set*:forKey:`.

Just found out this: https://github.com/Flipboard/FLEX/#nsuserdefaults-editing 😂
