### ISSUE TITLE
Swift print("demo") will not appear in System Log

### ISSUE THREAD

**Issue by liaolunhui** [FLEXTool/FLEX#452]
![IMG_9861](https://user-images.githubusercontent.com/13741751/87853944-d19c6900-c940-11ea-80c5-ab92c60b9c1e.PNG)

**Comment by NSExceptional** [comment]
Swift's `print()` does not go to the NSLog buffer, this screen only captures `NSLog()` calls

**Comment by NSExceptional** [comment]
A PR to add support for this is welcome! If you want to formally request this as a feature, please open a new issue.

**Comment by loinsir** [comment]
Hello! Would it be okay for me to work on this feature? @NSExceptional

**Comment by NSExceptional** [comment]
Sure

**Comment by loinsir** [comment]
I've created this PR to add Swift `print()` output capture support to FLEX System Log. Could you please review when you get a chance?

https://github.com/FLEXTool/FLEX/pull/724
