### ISSUE TITLE
menu and views are not showing on FLO app in South Korea iOS App Store

### ISSUE THREAD

**Issue by nanpuhaha** [FLEXTool/FLEX#462]
menu and views are not showing on FLO app in South Korea iOS App Store.

These are my iOS device and FLEX tweak that I use.
- FLEXer - invoke (Flipboard) FLEX from the statusbar (https://creaturecoding.com/repo/)
- iPad mini 5 iOS 13.5 Unc0ver jailbreak

The FLO app link is https://apps.apple.com/kr/app/id1129048043.

Please check the attached video.

**Comment by NSExceptional** [comment]
Try FLEXing on [my repo](https://nscake.github.io/). If the issue persists, open a new issue on [NSExceptional/FLEXing](https://github.com/NSExceptional/FLEXing)
