### ISSUE TITLE
iOS 14 Xcode 12 network history not working

### ISSUE THREAD

**Issue by beatman423** [FLEXTool/FLEX#466]
environment: iOS 14 Xcode 12
Network History not working

**Comment by evanemelgamoka** [comment]
Pretty sure this issue have been solved sometimes ago.

This is one of the first issue regarding network monitor in iOS 14:
https://github.com/FLEXTool/FLEX/issues/446

And this is the fix PR:
https://github.com/FLEXTool/FLEX/pull/451

There hasn't been another release since then though.

**Comment by BB9z** [comment]
The latest version 4.1.1 does not contain this fix. The latest code works for me.

If you use CocoaPods, change Podfile to this at this time.

```
pod 'FLEX', :git => 'https://github.com/FLEXTool/FLEX', :configurations => ['Debug']
```

**Comment by NSExceptional** [comment]
I guess I need to make a new release ASAP if that fix isn't in there! My bad!

**Comment by beatman423** [comment]
Thank you🙏

**Comment by wsalim1610** [comment]
Hey, any news on when the new release containing the fix will be up?

**Comment by pgodseSqsp** [comment]
Yes I noticed this issue as well on iOS 14. Any updates? -Thanks

**Comment by dmhts** [comment]
@NSExceptional It would be very much appreciated if you could do that in the near future. Thanks.
