### ISSUE TITLE
How to change encoding in network log for response body

### ISSUE THREAD

**Issue by RaziPour1993** [FLEXTool/FLEX#468]
{"title":"\u06f6\u06f0\u0645\u062a\u0631 \u0627\u062f\u0627\u0631\u06cc \u0642\u0648\u0644\u0646\u0627\u0645\u0647 \u0627\u06cc \u0635\u0627\u062f\u0642\u06cc\u0647"
}

**Comment by NSExceptional** [comment]
I'm not sure what you mean, can you elaborate?

**Comment by RaziPour1993** [comment]
Json It contains Persian and Arabic words.
When showing information, it does not show Persian words correctly
And shows as follows

{"title":"\u06f6\u06f0\u0645\u062a\u0631 \u0627\u062f\u0627\u0631\u06cc \u0642\u0648\u0644\u0646\u0627\u0645\u0647 \u0627\u06cc \u0635\u0627\u062f\u0642\u06cc\u0647"
}

**Comment by NSExceptional** [comment]
Press the settings gear on the network page and turn on "view JSON as dictionary" and you should be able to see the response as an NSString

**Comment by RaziPour1993** [comment]
![Simulator Screen Shot - iPhone 11 - 2020-10-05 at 18 46 07](https://user-images.githubusercontent.com/16708111/95098061-131c0380-073b-11eb-9fee-79ee03f1c1e6.png)

**Comment by NSExceptional** [comment]
If you copy the string and paste it somewhere, does it change to Arabic? Or is there a chance it's actually literally `\UXXX`?

**Comment by NSExceptional** [comment]
Let me know if you still need help with this and we can reopen the issue.
