### ISSUE TITLE
Some way to disable loading of FLEX at runtime

### ISSUE THREAD

**Issue by lilyball** [FLEXTool/FLEX#470]
I'd really like to be able to completely disable loading of FLEX at runtime, either with a launch argument (e.g. something that sets a volatile defaults key) or with an env variable.

The idea here is that I really don't need FLEX to be loading while running unit/UI tests in CI, especially given crashes like #469. It's meant to be an aid for exploring/debugging, not something that should be loaded when I'm running automated tests. But since building for testing is just doing a debug build, the test app includes FLEX.

In particular, what I'd like to do is disable fishhook, and anything else that runs at load time. The framework would still be linked into my app, so if I have code that programmatically shows it, that code will continue to link, but it's okay for FLEX to be nonfunctional if I actually try and show it with the runtime disabled (a quick hack might be for `showExplorer()` to simply do nothing and log an error if invoked with the runtime disabled, and of course the default simulator keyboard shortcuts shouldn't exist in this case though I assume disabling run-at-load behavior would do that already).

**Comment by matrush** [comment]
I'm also looking at this, I think it can be achievable by introducing some C preprocessor so it can be opt-in or opt-out when building.

**Comment by lilyball** [comment]
That would require me to pass a custom build setting flag to `xcodebuild` when building in CI, which is doable, but also prevents me from sharing any build artifacts with other builds (e.g. if I want to disable in unit testing but actually have it in UI testing for some reason, the two would have to independently rebuild the app).

I would much prefer a runtime check, so I can disable it without having to rebuild.

**Comment by matrush** [comment]
I'm not entirely sure if that's achievable since the current loads are done in the `+ (void)load` class method. It is invoked whenever a class or category is added to the Objective-C runtime; It is unlikely you can do any call to other parts of `FLEX` to tweak that behavior before it loads. So I think the preprocessor way is probably the most obvious solution. Please correct me if I'm wrong.

**Comment by lilyball** [comment]
I'm saying the `+load` methods should consult either an env var or `NSUserDefaults` to check for a predefined var/key whose presence signals "don't load FLEX". If this var/key is present, the `+load` method would then just exit without doing anything.

The `NSUserDefaults` method would be to allow the app to be launched with an argument like `-DisableFLEX YES` (which sets the user defaults key `"DisableFlex"` in the volatile `NSArgumentDomain`). The env var would just be something like `DISABLE_FLEX=1` and could be tested with a simple `getenv()` (for the env var I'd say treat the mere presence of the var as disabling it, e.g. `getenv("DISABLE_FLEX") != NULL`).

I'm not asking for a way for me to programmatically tweak the behavior, I'm asking for FLEX to define this env var or user defaults key itself.

**Comment by lilyball** [comment]
Apparently the `os_log` at-load stuff is [already gated by this](https://github.com/FLEXTool/FLEX/commit/a25ef87a5128be2af70691f5cb4e222520ab35c2) as of v4.1.0, but this wasn't in the release notes. But I'd like to disable all such functionality, not just the os_log stuff.

**Comment by NSExceptional** [comment]
I really like this idea, but I must point out that it is impossible to completely remove all possible side effects FLEX may have at runtime, because it adds a lot of categories on NSObject and other classes. These may or may not affect you, and most of them are prefixed, but some not (as of yet). Anyway, I'm not opposed to adding something like you've described for the reasons you've stated!

I must say though, for your use case, we typically advise users to `#if` their usage of FLEX and not include it in certain targets. I'm curious though, your use case sounds unique; does a rebuild (in your example) take a significantly longer time between the two test targets where one includes FLEX and one does not?

**Comment by chrisczupak** [comment]
I've been wanting this behavior as well and just put up a diff: https://github.com/FLEXTool/FLEX/pull/471

**Comment by lilyball** [comment]
@NSExceptional 

> I'm curious though, your use case sounds unique; does a rebuild (in your example) take a significantly longer time between the two test targets where one includes FLEX and one does not?

FLEX isn't in the test target. It's in the app target. The app has unit tests that use the app as the host. It's impossible to use `#if` for this because the app isn't built in any kind of special test configuration for unit tests, it's just built in the normal Debug configuration. Determining whether unit tests are running must be done at runtime (e.g. checking if XCTest.framework is loaded by looking for one of its classes, or looking for the undocumented `XCTestConfigurationFilePath` env var that controls the injection of the test bundle), which means it's too late to prevent linking in FLEX.

In theory we could pass build setting overrides when building in CI, but I really don't like that because it means FLEX will still be loaded when developers run unit tests locally.

As for categories, I'm not too concerned about their presence as long as they're all prefixed properly. The fact that some are not is pretty bad though.

**Comment by NSExceptional** [comment]
I see, I see! You're right, I wasn't thinking clearly about the target boundary.

I will try to have this resolved some time this weekend.
