### ISSUE TITLE
MobSF reported use of unsecured function 

### ISSUE THREAD

**Issue by Lakshaya** [FLEXTool/FLEX#472]
We have used MobSF client to analyse our app and it has reported the use of following unsecured functions which are used by flex

1. _printf/printf
2. _strlen/strlen
3. _memcpy/memcpy
4. calloc

**Comment by NSExceptional** [comment]
Does MobSF have safer replacements they suggest?

**Comment by Lakshaya** [comment]
_printf/printf
_strlen/strlen
_memcpy/memcpy
It suggest to remove these functions all together 
Use malloc function instead of calloc

**Comment by NSExceptional** [comment]
We cannot remove them all together. If you have suggestions for replacements (because there _are_ similar functions in the stdlib which accept tighter arguments) we can talk about those.

**Comment by NSExceptional** [comment]
Closing for now. Feel free to reopen when you address my last reply
