### ISSUE TITLE
The search bar does not appear in certain apps.

### ISSUE THREAD

**Issue by lint** [FLEXTool/FLEX#477]
I've noticed in several apps, when attempting to use FLEX, the search bar does not appear anywhere. For example, [here](https://imgur.com/oQJXmcm) is a screen recording of the issue, the app is [ChaoTimer](https://apps.apple.com/in/app/chaotimer-professional-cube-timer/id537516001) which was last updated 5 years ago. It just seems that the search bar is absent in every part of flex. Flex also takes up the entire screen in apps like this one instead of the UITransitionView effect which I normally see.

iPhone 6s, iOS 13.5, libFLEX 4.2.0

**Comment by NSExceptional** [comment]
I will look into this! I assume it has to do with the app being so old that none of my search bar code runs at all. FLEX supports down to iOS 10 I think, so if this app was last updated on iOS 8 or 9, that would explain it.

In the meantime, you can download an older version of libflex from my repo, `nscake.github.io`

**Comment by lint** [comment]
Great, thanks! Yes, I have noticed that this seemed to be happening on older apps. Your explanation makes so much sense. I had no idea that newer features were restricted on apps compiled on old SDKS, that's pretty neat. I do remember it going full screen and having a missing search bar went hand in hand. I don't think the full screen is really an issue, and yeah the swipe down does in fact exist and is convenient.

**Comment by NSExceptional** [comment]
So, this would likely involve hooking some UIKit code to change which version of the SDK it thinks the app has linked against. Imo this seems out of the scope of what FLEX should try to do… If you want to make a PR which does this, I would accept it though.

Sorry I couldn't be of more help :/

**Comment by lint** [comment]
Ah okay, I understand. Thank you for taking the time to look into it!
