### ISSUE TITLE
About swizzledSelectorForSelector Use Prefix

### ISSUE THREAD

**Issue by daybreak1024** [FLEXTool/FLEX#480]
I encountered a problem .That I hook the delegate of session , and found that **_cmd** was modified when I called back to the original delegate .
eg.
````
- (void)URLSession:(NSURLSession *)session task:(NSURLSessionTask *)task didCompleteWithError:(nullable NSError *)error {
    // do something
    // _cmd is ' _flex_swizzle_*_URLSession:task:didCompleteWithError:', respondsToSelector will return false.
    if ([self.realDelegate respondsToSelector:_cmd]) {
        [self.realDelegate URLSession:session task:task didCompleteWithError:error];
    }
}
````

So, I want to know why you need to do this processing here ?
````
+ (SEL)swizzledSelectorForSelector:(SEL)selector {
    return NSSelectorFromString([NSString stringWithFormat:
        @"_flex_swizzle_%x_%@", arc4random(), NSStringFromSelector(selector)
    ]);
}
````
Thanks in advance .

**Comment by daybreak1024** [comment]
I think **_cmd** is the default behavior of the system and should not be modified.

Maybe it should call back **selector** instead of **swizzledSelector**.
````
SEL selector = @selector(**);
SEL swizzledSelector = [FLEXUtility swizzledSelectorForSelector:selector];

DidBecomeDownloadTaskBlock implementationBlock = ^(id<NSURLSessionDataDelegate> slf,
                                                       NSURLSession *session,
                                                       NSURLSessionDataTask *dataTask,
                                                       NSURLSessionDownloadTask *downloadTask) {
        [self sniffWithoutDuplicationForObject:session selector:selector sniffingBlock:^{
            undefinedBlock(slf, session, dataTask, downloadTask);
        } originalImplementationBlock:^{
            ((void(*)(id, SEL, id, id, id))objc_msgSend)(
// Maybe it should call back **selector** instead of **swizzledSelector**. 
                slf, swizzledSelector, session, dataTask, downloadTask
            );
        }];
    };
````

**Comment by NSExceptional** [comment]
FLEX swizzles some methods to intercept network traffic. You should use the actual `@selector()` you want to check for and not `_cmd` because `_cmd` can change when the method is swizzled or even be omitted.

**Comment by daybreak1024** [comment]
> FLEX swizzles some methods to intercept network traffic. You should use the actual `@selector()` you want to check for and not `_cmd` because `_cmd` can change when the method is swizzled or even be omitted.

In my understanding, _cmd should be the selector of the current method, but it has now been modified. I don’t think this is reasonable, so I want to communicate the reasons why it must be done.

**Comment by NSExceptional** [comment]
> In my understanding, _cmd should be the selector of the current method, but it has now been modified.

This is how Objc works fundamentally. You can take any method implementation and add it as a new method with a new name, and when you call it by that new name, `_cmd` will reflect that.

You shouldn't rely on the contents of `_cmd` always being the same for a particular piece of source code.

**Comment by daybreak1024** [comment]
No offense,Bickering.Just do some related discussions for learning.

I think there is no problem with my understanding.

I found a description in  [developer apple](https://developer.apple.com/documentation/objectivec/nsobject/1418637-doesnotrecognizeselector).
> "The _cmd variable is a hidden argument passed to every method that is the current selector;"

Finally, thanks for your reply.

**Comment by NSExceptional** [comment]
[https://nshipster.com/method-swizzling/](https://nshipster.com/method-swizzling/)

**Comment by daybreak1024** [comment]
Thanks for your reply.

I ignored this.

**Comment by NSExceptional** [comment]
Please don't ever open another issue here again if you're going to be this disrespectful.

**Comment by daybreak1024** [comment]
Fist at all. 
I didn't mean any offense.

If it is "ignored", it may be because my mother tongue is not English. I used the wrong word and should use forget.

If it is other, it may be because the hook method I use does not have such a problem, so it is not considered.
eg. 
````
BOOL zlm_SwizzleMethodAndStore(Class class, BOOL isClassMethod, SEL original, IMP replacement, IMP* store) {
    
    if (class == nil || original == nil) {
        return NO;
    }
    
    IMP imp = NULL;
    Method method = NULL;
    if (isClassMethod) {
        method = class_getClassMethod(class, original);
    } else {
        method = class_getInstanceMethod(class, original);
    }
    
    if (method != NULL) {
        IMP originalImp = method_getImplementation(method);
        if (store) {
            *store = originalImp;
        }
        imp = method_setImplementation(method, (IMP)replacement);
    } 
    
    return (imp != NULL);
}
````
And I was trying to deal with FLEX in this way. I encountered a problem and found that each class needs to maintain a store, so I gave up the idea of submitting.

I apologize for my unintentional offense, maybe I should change to a translator.

**Comment by NSExceptional** [comment]
Oh, I see, my apologies. I thought you were saying you were going to ignore my reply! I misunderstood you.

FLEX could probably do what you are doing there, yes, but still advise you to use `@selector(...)` instead of `_cmd` 😅

I think we use swizzling and not booking because it is easy to "undo" swizzled methods by simply swizzling them again. This allows us to turn the network monitor on and off at will. This could probably be done by using `method_setImplementation` as well, but a change like this would not be high on my list of priorities so I can't promise it anytime soon

**Comment by daybreak1024** [comment]
That's ok, My expression is unreasonable.

I will follow your suggestions to deal with `_cmd`.

And thank you for taking the time and discussing with me has deepened my understanding of runtime.

**Comment by NSExceptional** [comment]
You're welcome! Please, feel free to ask about anything else or even email me if you want help with something.
