### ISSUE TITLE
Please add copy from description

### ISSUE THREAD

**Issue by Chertovski** [FLEXTool/FLEX#481]
![2020-11-06 23 17 40](https://user-images.githubusercontent.com/47669432/98411027-61982700-2086-11eb-98c5-d1e26fc3f3a2.jpg)

**Comment by NSExceptional** [comment]
For now you can press the share button to copy the description but I do need to add the context menu back to the row

**Comment by Chertovski** [comment]
yeah please return context menu back to the row
