### ISSUE TITLE
FLEX Objects not deallocated from the memory

### ISSUE THREAD

**Issue by Ram4096** [FLEXTool/FLEX#483]
I've discovered that there are some objects that are never deallocated from the memory.  
For example, let's try with FLEXScopeCarousel.

1. Open FLEX > Heap Objects.
2. Search "FLEXScopeCarousel": you can see there is 1 instance.
3. Swipe back.
4. Reopen Heap Objects.
5. Search "FLEXScopeCarousel": now there are two instances, but the previous one should be destructed.  

When swiping back from Heap Objects (or other controllers that use FLEXScopeCarousel), FLEXScopeCarousel should be deallocated from the memory. The same for cells into FLEXScopeCarousel that are never deallocated.  
The same issue happens with other objects, like FLEXLiveObjectsController.

**Comment by NSExceptional** [comment]
I swore someone already opened an issue for this but I can't find it. Anyway, I'm aware of the issue but I don't know what is causing it :( help wanted

**Comment by Ram4096** [comment]
Oh! I hope we figure out a solution!  
If I swipe back I still see FLEXScopeCarousel. If I check "See Objects with References to This Object" I see a lot of things about "AutoLayout", in particular the ivars "id _referenceItem" and "id _delegate".  
As personal experience, when I discover some objects that are never automatically deallocated (in ARC mode), I manually set all "id" values to nil in "viewDidDisappear", when the view "isMovingFromParentViewController" and it works. 
 
Maybe can a similar technique help here too?

**Comment by NSExceptional** [comment]
Fixed! Thanks again!

**Comment by Ram4096** [comment]
This bug is back. I suppose it happens because the search bar is active. Can you try setting the search controller to inactive (searchController.active = NO) when the view is disappeared?
