### ISSUE TITLE
FLEX crashes when viewing classes that represent controllers.

### ISSUE THREAD

**Issue by Ram4096** [FLEXTool/FLEX#485]
After the recent update of FLEX, every time I try to view a class that represents a controller, FLEX crashes.  

To fix the crash, I've manually added the following class methods:
```
+(id)navigationController;  
+(id)viewIfLoaded;  
```
These methods shouldn't  obviously be class methods, but I suppose FLEX tries to call them in a part of the code, when the user is inspecting a class. Just check if the object is a class or an instance before calling those methods.

**Comment by NSExceptional** [comment]
Which version of FLEX are you on? There was an update recently where a contributor changed some code and broke something like this unintentionally

**Comment by Ram4096** [comment]
I'm using the latest 4.2.2 version available on Cydia

**Comment by NSExceptional** [comment]
This is already fixed and will be in the next update, 4.3
