### ISSUE TITLE
Network activity of other applications

### ISSUE THREAD

**Issue by egegrsn** [FLEXTool/FLEX#486]
Hello there,

Firstly, you are doing an incredible work here! Thanks for all your effort. I wonder if I can view other applications' or all systems network activities from the app I added Flex framework. Is it possible or not? 

Best Regards,

Ege.

**Comment by NSExceptional** [comment]
You cannot do this from your own app. If you want to inspect traffic of the system or other apps, try using Charles Proxy on the App Store.
