### ISSUE TITLE
FLEX network logger is not working on iOS14

### ISSUE THREAD

**Issue by yongyuegao** [FLEXTool/FLEX#492]
I tried the latest tag and  master, but network logger is still not working on iOS14.

**Comment by NSExceptional** [comment]
I'm on iOS 14 and it is working. Can you provide more details about your use case? Are you trying to view web view requests or NSURL* calls?

**Comment by NSExceptional** [comment]
Closing this since it is likely a duplicate of #293. If you're NOT trying to inspect `WKWebView` traffic, let me know and we can reopen this.

**Comment by NSExceptional** [comment]
Locking this in favor of a discussion since this is a common issue. Please direct further comments to #495.
