### ISSUE TITLE
Public Interface

### ISSUE THREAD

**Issue by Sudarshanshetty** [FLEXTool/FLEX#496]
@interface UIView (FLEX_Layout)

- (void)centerInView:(UIView *)view;
- (void)pinEdgesTo:(UIView *)view;
- (void)pinEdgesTo:(UIView *)view withInsets:(UIEdgeInsets)insets;
- (void)pinEdgesToSuperview;
- (void)pinEdgesToSuperviewWithInsets:(UIEdgeInsets)insets;
- (void)pinEdgesToSuperviewWithInsets:(UIEdgeInsets)insets aboveView:(UIView *)sibling;
- (void)pinEdgesToSuperviewWithInsets:(UIEdgeInsets)insets belowView:(UIView *)sibling;

@end

Above interfaces are public. so it usually shows in the auto completion in our internal projects (sometimes without knowing its a felx method we use it, later it crashes in release build ) but we don't want to use these method since we are not adding Flex in release builds. so if we can make this internal to Flex it will be awesome.

**Comment by NSExceptional** [comment]
I will do that, I thought it was internal already, my apologies!

**Comment by Sudarshanshetty** [comment]
Awesome, If your busy let me know. i can create a PR for the same.

**Comment by NSExceptional** [comment]
I prefixed them and I also hid this particular category from FLEX.h so the new methods shouldn't even show up in autocomplete.

**Comment by Sudarshanshetty** [comment]
Thanks @NSExceptional
