### ISSUE TITLE
Unable to open FLEX in system applications and SpringBoard

### ISSUE THREAD

**Issue by lint** [FLEXTool/FLEX#503]
### Environment
- Platform+version: **iPhone 11 pro max, iOS 13.5** 
- FLEX version: **4.4.0** 
- FLEXing version: **1.3.1**
- FLEXall version: **0.0.1-21** (I know you are not the author of FLEXall, but the issue was present with that loader as well)

### Bug Report

I am unable to open FLEX in several system apps such as Settings, Notes, Weather, Safari, Music, etc. It also does not appear in SpringBoard on the lockscreen or homescreen. I tried both methods of invoking FLEX, the three-finger hold or holding on the status bar, neither work. Downgrading to libFLEX 4.3.0 fixes the issue.

**Comment by NSExceptional** [comment]
Downgrade libflex. Sorry about this, it's arm64e being a pain in my booty. I will tweet when I fix this version

**Comment by lint** [comment]
No worries, appreciate it!
