### ISSUE TITLE
Make weakify macro private

### ISSUE THREAD

**Issue by revolter** [FLEXTool/FLEX#504]
### Environment
- Platform+version: **iOS 14** 
- FLEX version: **9.9.9** 

### Bug Report

The `weakify` macro is defined in a public header file:

https://github.com/FLEXTool/FLEX/blob/947769f6f9ef277b34911eeaf7df35e9e7b0494e/Classes/Utility/FLEXMacros.h#L16

but only used in private implementations. So it (and maybe others, too) could and should be moved to an internal header file, because it clashes with out own definitions:

```
<redacted>/Macros.h:59:9: 'weakify' macro redefined
```

**Comment by NSExceptional** [comment]
Will be fixed in the next release! Committed but not pushed yet. I just made the whole header private.
