### ISSUE TITLE
Bottom menu often fails to pop up for adding bookmarks

### ISSUE THREAD

**Issue by badger200** [FLEXTool/FLEX#507]
### Environment
- Platform+version: **iOS 12.4** 
- FLEX version: **4.4.0** 

### Bug Report

I mainly use an iPad Pro iOS 12.4, unc0ver 5.3.1, Substitute 2.0.7 but this bug has been an issue for a long time, possibly forever. 

I cannot discern a pattern as to what dictates which scenarios/apps the menu will fail to pop up, but I can say:

- If it fails to pop up, none of the 3 bottom FLEX menus will pop up. (Always)

- if it pops up as expected, it seems to reliably continue working in that app. 

The issue reminds me of some issues I have experienced with other apps failing or crashing due to popoverPresentation-missing/related errors, that seem to be due to the fact I’m using an iPad with apps that are iPhone specific, like Instagram. 

I run a killer tweak called PerfectFit by Tony Kraft which somehow tricks/forces iPhone apps like Instagram to operate in glorious full screen iPad retina. But this seems to confuse Instagram in a few small cases where UI elements will be clearly mislocated (top nav bar elements cluttered on the far left instead of spread out like normal.)

**Comment by NSExceptional** [comment]
Just to be clear, you're referring to any of [these action sheets,](https://user-images.githubusercontent.com/8371943/108240600-a06f5b80-7110-11eb-9020-a07b2b15e77b.jpeg) right?

**Comment by badger200** [comment]
Yes precisely. 

And I edited my comment, I’m actually on 4.4.0.

**Comment by badger200** [comment]
Aha!!! I found a major clue!! This bug is reproducible when I have the FLEX toolbar visible, tap a command in an app that downloads an image for 2-10 seconds, and then pops up a completion dialog with 2 button choices. I tap the OK button to dismiss the dialog, and from that point onward, FLEX will fail to pop up those 3 bottom Bookmark menus.

See the next Issue I’m about to file as it seems quite related to this.

**Comment by NSExceptional** [comment]
Closing in favor of #519
