### ISSUE TITLE
Long press to Copy text no longer works reliably

### ISSUE THREAD

**Issue by badger200** [FLEXTool/FLEX#508]
### Environment
- Platform+version: **iOS 12.4** 
- FLEX version: **4.4.0** 

### Bug Report

Sometime since perhaps 6 months ago (4.1?) the long-press top text field to pop up a black “Copy” button, began to malfunction. 

Prior to this, anytime you had text in the big top white box, you could always long press and always get a Copy button.  

But now it only works maybe....50-75% of the time. I’m not sure what the distinction is between scenarios where it works vs those where it doesn’t, but when it fails, I have to dig deeper into the variables and properties to find a plaintext string I can copy, instead of those URL-encoded or escape sequence noisy ones.

**Comment by NSExceptional** [comment]
I'm not sure which box you're referring to, the object description?

**Comment by badger200** [comment]
> I'm not sure which box you're referring to, the object description?

Yes. Wish I could pinpoint when it fails.

**Comment by NSExceptional** [comment]
This functionality has moved to the share icon in the toolbar as a part of a larger refactoring, but I've been wanting to add it back so that you can just long press on it like before, as I prefer that method as well.

Closing this for now, but it is on my todo list for the future.
