### ISSUE TITLE
Run Flex in a real device

### ISSUE THREAD

**Issue by remlostime** [FLEXTool/FLEX#513]
Hi,
I am wondering that is it possible to run it on real device? If my device is not connected to the computer, how to trigger it?

**Comment by tinder-owenthomas** [comment]
You can trigger it programmatically any way you want. In our codebase we have it set to a specific tap combination (for DEBUG builds only). You could also expose a button that only exists in debug builds to launch it, or any other way you choose. 

See https://github.com/FLEXTool/FLEX#usage
