### ISSUE TITLE
Version 4.4.0 is not working with iOS 13 due to the update of clang/LLVM in Xcode 12

### ISSUE THREAD

**Issue by haoict** [FLEXTool/FLEX#515]
### Environment
- Platform+version: **iOS 13.7**
- FLEX version: **4.4.0** 

### Bug Report

The version 4.4.0 is not working with iOS 13. Probably due to the update of clang/LLVM in Xcode 12

More detail: https://gist.github.com/haoict/96710faf0524f0ec48c13e405b124222

**Comment by NSExceptional** [comment]
Closing this as I think I resolved it for now. I assume you're referring to the jailbreak tweaks. Feel free to reopen it if this issue persists on `4.4.1` from my repo.
