### ISSUE TITLE
There is a crash on iOS 13.

### ISSUE THREAD

**Issue by jongwonatwork** [FLEXTool/FLEX#523]
### Environment
- Platform+version: **iOS 13.3**
- FLEX version: **4.4.1**

### Bug Report
Our app has been crashed whenever it starts.
There are some crash logs.
I think this crash is related to your latest update about shorcuts.
```
*** Assertion failure in +[FLEXProperty named:onClass:], FLEXProperty.m:49
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Cannot find property with name image on class UIAlertController'
*** 
```
Please fix it~

**Comment by NSExceptional** [comment]
Hi,

Can you remove the pod, run `pod repo update`, then install the pod again?

I published the wrong commit and I was made aware of this by someone earlier, and I have since deleted the old version from cocoapods and replaced it with the fixed version.

**Comment by nathsociete** [comment]
Hi,

I have got the same issue.
Removing the pod and then run _pod repo update_ does not help for me...

**Comment by jongwonatwork** [comment]
@NSExceptional 
Hi, thanks for your reply.

I downgraded the FLEX pod to 4.4.0, then update the pod again.
It fixed the problem.

1. adding version
```
pod 'FLEX', '<= 4.4.0'
```
2. downgrading the pod
3. removing version
4. updating the pod
