### ISSUE TITLE
Cannot find property with name image on class UIAlertController

### ISSUE THREAD

**Issue by karmamaster** [FLEXTool/FLEX#525]
### Environment
- Platform+version: **iOS 12.5.1** 
- FLEX version: **4.4.1** 
- Just only use flex release lib

### Bug Report

When I running the tool which built along with Classes files in FLEX lib, the issue showing as: (you can check the screenshot to get complete log)

`'Cannot find property with name image on class UIAlertController`

This is the screenshot:
![issue](https://user-images.githubusercontent.com/9405054/113354170-f4ed3400-9368-11eb-8c1e-fcb21c88e707.PNG)

but when I tried to run this FLEX lib (version 4.4.1) on ios version 14.4.1, the tool is starting well but it is hanging phone system when tool trying to run all system command like: "ls, killall, cd...e.t.c.." 

Please take a look at it.

**Comment by NSExceptional** [comment]
See #523

**Comment by karmamaster** [comment]
Hello,
Now its run fine with your new commit for 4.4.1, but when i tried to run the killall command on machine its make the system not responding to every command that I called manually or by the code. Can you take a look at it? This is the testing eviroment:

Machine: iphone 5s (12.5.1) / iphone 6s (14.4.1)
Flex version: 4.4.1

This issue is occurring on both 6s and 5s iphone.

**Comment by NSExceptional** [comment]
Try posting on /r/jailbreak
