### ISSUE TITLE
@available wasn't working properly

### ISSUE THREAD

**Issue by LNSSPsd** [FLEXTool/FLEX#526]
### Environment
- Platform+version: **iOS 13.3** 
- FLEX(libFLEX) version: **4.4.1** 

### Bug Report
Apps that loaded FLEX crash with error message `Cannot find property with name image on class UIAlertController`.  
The message mentioned `image` property so I tried to comment the line
```
[alertControllerProps insertObject:@"image" atIndex:4];
```
and FLEX works properly.  
But this line shouldn't be executed because there's an `@available` before it and my system version is lower than iOS 14, so it seems that the `@available` doesn't work properly(it returns true even if my system version doesn't match the requirement).  
I tried to change `@available(iOS 14.0, *)` to `[NSProcessInfo.processInfo isOperatingSystemAtLeastVersion:(NSOperatingSystemVersion){14,0,0}]` and uncomment the code previously mentioned and FLEX also works fine.

**Comment by NSExceptional** [comment]
Are you using the tweak as your info suggests or are you using it as a cocoapod in a project?

**Comment by LNSSPsd** [comment]
All of them including SpringBoard.

**Comment by NSExceptional** [comment]
I didn't release 4.4.1 yet, did you build it yourself? Are you sure you were on the same commit that `FLEX/master` points to now? Because at first I didn't have that availability check at all, and then I added it the next day and forced pushed and silently changed the tag 😬

So if you unknowingly compiled the version without the check, that would explain what we're seeing here. There's no reason that check wouldn't work on iOS 13

**Comment by LNSSPsd** [comment]
I compiled it using the latest version,and I also saw the `@available` locally,but is doesn't work at all.

So now I think maybe something was configured wrongly in my compiler or other things.

Thanks for answering.

**Comment by NSExceptional** [comment]
Well hey, no reason to close the issue yet, let's figure this out. Can you send me the dylib from your compiled version of the package?

**Comment by LNSSPsd** [comment]
Oh thanks, here's what I've attempted.
Dylib that built from version `commit 258ec869` w/ my compiler: [libFLEX_dylib.zip](https://github.com/FLEXTool/FLEX/files/6284684/libFLEX_dylib.zip)  
Environment: Debian Linux,Theos 2.5.0
I tried to debug it using IDA, and it seems that the availability check doesn't exist in the binary and the action which inserts
`"image"` into `alertControllerProps` will be called whatever.
![Screenshot1](https://user-images.githubusercontent.com/24724395/114161157-578e9300-995a-11eb-99aa-5d4dfa77a0c9.png)
![Screenshot2](https://user-images.githubusercontent.com/24724395/114161476-b18f5880-995a-11eb-9544-0d08fb437690.png)
And this is the code at that place.^  
But when I replace the `@available` expression to `[NSProcessInfo.processInfo isOperatingSystemAtLeastVersion:]` and the code can be compiled correctly.
(IDA:
![Screenshot3](https://user-images.githubusercontent.com/24724395/114162751-fbc50980-995b-11eb-8532-be34682abab9.png)
)  
and the modified code's image:
![Screenshot_4](https://user-images.githubusercontent.com/24724395/114162802-05e70800-995c-11eb-8ae9-fb70857a8de2.png)

**Comment by NSExceptional** [comment]
I think this has to be a linux thing. Looking at your binary, I don't see any calls to `___isPlatformVersionAtLeast`, while mine has a call to it. Yours just has a weird `if ((0xff & 0x1) == 0x1)` check (or no check at all in the arm64e slice).

Can you try compiling it on macOS? If not, just hang on and I'll update my package

**Comment by LNSSPsd** [comment]
I don't have a device with macOS installed.
But thank you for figuring out the cause of the problem.

**Comment by NSExceptional** [comment]
The only other thing it could be is if you modified the makefile to use iOS 14 as the minimum deployment version
