### ISSUE TITLE
Crash when opening view hierarchy view in SpringBoard | `Invalid parameter not satisfying: depthsForViews.count == allViews.count`

### ISSUE THREAD

**Issue by Galactic-Dev** [FLEXTool/FLEX#527]
### Environment
- Platform+version: **iOS 14.3**
- libFLEX version: **4.4.0** 
- FLEXall version **0.0.1-21**

### Bug Report
- Crash log: https://haste.zneix.eu/aqumetunoq
- It happens when tapping the "views" button on the FLEXall bar. It only happens for me when I'm adding the view of a view controller to another view in SpringBoard. Both view controllers are Apple classes, and it adds the view just fine with no issues, except for when I try to open the "views" tab in FLEXall. I tried using FLEXing as well, but the same crash occured. Maybe the issue is in the way I'm initializing the view controller because its a pretty complex one.

**Comment by NSExceptional** [comment]
I guess I misread your issue the first time, but you are potentially doing something wrong: you have to remove the view from its superview first. Closing this issue as the button works fine for me on several iOS versions
