### ISSUE TITLE
Can't compile version 4.4.1 through Carthage for deployment target iOS 10 as XCFramework

### ISSUE THREAD

**Issue by CochiorasBogdan** [FLEXTool/FLEX#528]
### Environment
- Platform+version: **iOS 10** 
- FLEX version: **4.4.1** 

### Bug Report

I am trying to compile FLEX through Carthage in a project that has the target version iOS 10 (it seems it fails to compile arhitecture armv7). I don't think the issue that I have is related to the target version but to a change from this commit https://github.com/FLEXTool/FLEX/commit/bcc04f4113ca7cec98ca4836633bca299758a8ad#diff-96cb7534c2d0ce0fb4f2fcdce407e33139d6193500044bfcdb8b4d2cc5153713

When I compile the project with Carthage 0.37.0 command `carthage update FLEX --use-xcframeworks --platform iOS` it fails to archive with the following error:
```
The following build commands failed:
	CompileC /Users/SomeUser/Library/Caches/org.carthage.CarthageKit/DerivedData/12.4_12D4e/FLEX/4.4.1/Build/Intermediates.noindex/ArchiveIntermediates/FLEX/IntermediateBuildFilesPath/FLEX.build/Release-iphoneos/FLEX.build/Objects-normal/armv7/FLEXShortcutsFactory+Defaults.o /Users/SomeUser/Projects/SomeApp/dev/Carthage/Checkouts/FLEX/Classes/ObjectExplorers/Sections/Shortcuts/FLEXShortcutsFactory+Defaults.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/SomeUser/Library/Caches/org.carthage.CarthageKit/DerivedData/12.4_12D4e/FLEX/4.4.1/Build/Intermediates.noindex/ArchiveIntermediates/FLEX/IntermediateBuildFilesPath/FLEX.build/Release-iphoneos/FLEX.build/Objects-normal/armv7/FLEXObjectExplorerFactory.o /Users/SomeUser/Projects/SomeApp/dev/Carthage/Checkouts/FLEX/Classes/ObjectExplorers/FLEXObjectExplorerFactory.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(2 failures)
```
I don't have any issues with the previous version. Maybe the private header is not visible or something like that? Not sure exactly how to debug this kind of issues.

**Comment by lexrus** [comment]
We can't even build the FLEX.xcodeproj with Xcode. The following files are missing from the project file.
<img width="1022" alt="Screen Shot 2021-04-16 at 11 30 54 PM" src="https://user-images.githubusercontent.com/219689/115048229-ecb9fa80-9f0b-11eb-9cff-426916bb46b7.png">
<img width="1052" alt="Screen Shot 2021-04-16 at 11 34 07 PM" src="https://user-images.githubusercontent.com/219689/115048562-47ebed00-9f0c-11eb-961c-d06a188e73d7.png">

I just built FLEX.xcframework right after adding these files manually.

@NSExceptional Could you fix the project file?

**Comment by NSExceptional** [comment]
Can you pull from master? This is fixed on master but not in any tag
