### ISSUE TITLE
How to add for bazel swift project

### ISSUE THREAD

**Issue by MichaelGofron** [FLEXTool/FLEX#533]
I'm trying to add flex to a project but when I drag the folder classes or the project to the folder as explained in the manual section it doesn't seem to work when I press "f". 

Is there some other way to add the project to a bazel built project or some step with manually adding it that I'm not doing correctly?

**Comment by NSExceptional** [comment]
I'm sorry, I don't know anything about Bazel. I'm going to close this. Would you like me to convert this issue to a discussion so maybe others with the same issue can help you?
