### ISSUE TITLE
FLEX Explorer could move its position if it's covered by keyboard

### ISSUE THREAD

**Issue by matrush** [FLEXTool/FLEX#535]
Currently the FLEX Explorer is showing behind the keyboard, which made it inaccessible. Ideally FLEX should listen to the keyboard frame changes and move itself up a bit to be visible.

**Comment by badger200** [comment]
I second this, I have had a handful of scenarios where the positioning of the FLEX toolbar left me at a UI-dead-end. But I understand if it's not fixable.

**Comment by NSExceptional** [comment]
It is fixable, just hasn't been a priority for me compared to other bugs and features. PRs welcome!
