### ISSUE TITLE
libFLEX crashes when opening the keychain.

### ISSUE THREAD

**Issue by Ram4096** [FLEXTool/FLEX#537]
### Environment
- Platform+version: **iOS 14.3**
- FLEX version: **4.4.0**

### Bug Report

```
'NSInvalidArgumentException', reason: '-[__NSCFData isEqualToString:]: unrecognized selector sent to instance
```

**Comment by NSExceptional** [comment]
I believe this will be fixed in the next release thanks to cf2e94a. Please let me know if it isn't!
