### ISSUE TITLE
Calling method using curly quotation mark (default on iOS keyboard since iOS 11) instead of ASCII failed

### ISSUE THREAD

**Issue by yur1xpp** [FLEXTool/FLEX#544]
### Environment
- Platform+version: **iOS 14.3** 
- FLEX version: **4.4.0** 

### Bug Report

AFAIK since iOS 11 default quotation mark (smart punctuation) on the keyboard (Settings -> General -> Keyboard -> Smart Punctuation) are the curly ones (`‘’` and `“”`) instead of the ASCII (`'` and `"`), FLEX however unable to process them when they are used in method calling value and will fall back to `nil`, would it be possible to filter/re-encode them upon calling?

**Comment by NSExceptional** [comment]
Looks like as of iOS 11 there is an option to do this automatically. Outside of that you'll have to just turn the setting off yourself. Thanks for bringing this up!
