### ISSUE TITLE
Toolbar should not disappear on method call screen

### ISSUE THREAD

**Issue by yur1xpp** [FLEXTool/FLEX#546]
### Environment
- Platform+version: **iOS 14.3** 
- FLEX version: **4.4.0** 

### Bug Report

When trying to call method especially the ones with that have many input input arguments, the tool bar at the bottom that host the "Call" button automatically hidden and not reappearing again no matter scrolling the view up or down, effectively making calling the method impossible. One suggestion is to never hide the bottom tool bar. I also noticed that quite often the text field for input arguments are also unresponsive after changing between "Value" and "Address", not sure if it's somehow related to the same bug.

[https://imgur.com/a/vMOCTs2](
 https://imgur.com/a/vMOCTs2)

**Comment by NSExceptional** [comment]
If you tap the navigation bar it will reappear, but yeah I need to make it so the toolbar will not ever disappear on that screen.
