### ISSUE TITLE
iOS min version 13.0

### ISSUE THREAD

**Issue by apps4everyone** [FLEXTool/FLEX#549]
The latest release notes include:

Drop support for iOS 12 SDK

but there are 9.0/10.3 in podspec / IPHONEOS_DEPLOYMENT_TARGET values.

**Comment by apps4everyone** [comment]
and the Example Project has 13.2 -> 13.0 or all 13.2?

**Comment by NSExceptional** [comment]
This just drops support for compiling it with the iOS 12 SDK (AKA Xcode 10). It does not change the minimum supported iOS version :)

**Comment by apps4everyone** [comment]
ok, thx
