### ISSUE TITLE
Freezing in the TikTok app

### ISSUE THREAD

**Issue by objc-class** [FLEXTool/FLEX#561]
### Environment
- Platform+version: **iOS 14.3**
- FLEX version: **4.5.0**

### Bug Report

The screen will freeze when the 'views' button is clicked in the TikTok app

**Comment by RipGlock** [comment]
I came just to find if there was a fix for this yet. Dont know the reason, cant even dump the classes and headers using flex 3 so idrk what to do

**Comment by NSExceptional** [comment]
It's not freezing, but the view's window is kinda broken. After inspecting the app, it looks like Tik Tok is subclassing some of my classes at runtime and intentionally breaking them.

If you want to inspect the view hierarchy, you can debug the app with Xcode.
Just open any Xcode project and go to _Debug_ > _Attach to Process…_ > and choose Tik Tok, then [click the Debug View Hierarchy button](https://developer.apple.com/library/archive/documentation/ToolsLanguages/Conceptual/Xcode_Overview/ExaminingtheViewHierarchy.html)
