### ISSUE TITLE
[Buck] Error: file not found with <angled> include; use "quotes" instead

### ISSUE THREAD

**Issue by matrush** [FLEXTool/FLEX#584]
### Environment
- Platform+version: **iOS 15**
- FLEX version: **4.6.1**

### Bug Report
Got a lot of error like this after this change https://github.com/FLEXTool/FLEX/commit/2f9f2664930c9a093e724f9c5f455649c1976d5a
I'm using BUCK so it's probably not the exact environment that the projects uses by default, however it would still be good to fix for all.
```
error: 'FLEXDefaultsContentSection.h' file not found with <angled> include; use "quotes" instead
#import <FLEXDefaultsContentSection.h>
```
We should be using `#import "xxx.h"` instead of `#import <xxx.h>` as the latter look only in the standard system directories.
See
https://gcc.gnu.org/onlinedocs/cpp/Search-Path.html
https://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename

**Comment by NSExceptional** [comment]
This change was made to appease SPM I believe; could really use some help here, I'm not sure how to reconcile the imports and build settings in a way that makes all build systems happy 😵‍💫

**Comment by matrush** [comment]
> This change was made to appease SPM I believe; could really use some help here, I'm not sure how to reconcile the imports and build settings in a way that makes all build systems happy 😵‍💫

What does SPM requires? It is not happy with `#import "xxx.h"`?

**Comment by NSExceptional** [comment]
Not for the framework headers it's not

**Comment by NSExceptional** [comment]
Are you building FLEX as a standalone target or are you including the source directly in your project?

**Comment by NSExceptional** [comment]
I think #597 may resolve this; closing for now, feel free to reopen if the issue persists
