### ISSUE TITLE
Xcode 13.3  run  ,   crashed in flex_fishhook

### ISSUE THREAD

**Issue by nightfuryChen** [FLEXTool/FLEX#587]
Xcode 13.3  run  ,   crashed in flex_fishhook  153 line.

indirect_symbol_bindings[i] = cur->rebindings[j].replacement;

Thread 1: EXC_BAD_ACCESS (code=2, address=0x1ec83bb00)

**Comment by NSExceptional** [comment]
I can't run 13.3 on my mac, I'm gonna need some help. Do you have a crash log?

**Comment by NSExceptional** [comment]
I'm unable to reproduce this. I will reopen the issue if you can help.
