### ISSUE TITLE
Missing SPM Package.swift file in tagged versions

### ISSUE THREAD

**Issue by flejmer** [FLEXTool/FLEX#588]
### Environment
- FLEX version: 4.6.1

### Bug Report

I checked tagged versions and it seems `Package.swift` file is missing for each of them. Here is link to version [4.6.1](https://github.com/FLEXTool/FLEX/tree/4.6.1) as an example.

This creates an issue when I'm trying to fetch FLEX with tuist project generation tool. I'm getting error `no Package.swift manifest for version 4.6.1`.

[Here is link](https://github.com/tuist/tuist/issues/4249) to issue I created on tuist repo regarding adding FLEX to project.

**Comment by Demircivi** [comment]
Bump, this is still the case.

**Comment by wangkunzhen** [comment]
Bump, it still doesn't work.

**Comment by NSExceptional** [comment]
I'll get on this today, I'm sorry

**Comment by NSExceptional** [comment]
Published 4.7.0!
