### ISSUE TITLE
UIView support relative item

### ISSUE THREAD

**Issue by zhlinh** [FLEXTool/FLEX#591]
UIView suport relative item, shows distance of two views

**Comment by NSExceptional** [comment]
I don't understand what exactly you're asking for, can you elaborate?

**Comment by NSExceptional** [comment]
I can reopen this when you respond

**Comment by zhlinh** [comment]
Just like this
![vD5X21I7Yf](https://user-images.githubusercontent.com/7844628/164880578-fc4c1706-ad8f-4592-acad-5c818818cc00.jpeg)
