### ISSUE TITLE
Export class info like class-dump.

### ISSUE THREAD

**Issue by nanpuhaha** [FLEXTool/FLEX#594]
Is it able to export specific or all classes informations into dump-file like class-dump?

Flex is much better than any other classdumps, but I want to save as file.

**Comment by NSExceptional** [comment]
This is out of the scope of this project imo, but I encourage you to build some kind of extension to FLEX that does this! FLEX tries its best to be very extensible. Let me know if you have any API feature requests that would make it easier.
