### ISSUE TITLE
UI is Broken , All Buttons overlap and unable to click

### ISSUE THREAD

**Issue by sujata23** [FLEXTool/FLEX#596]
### Environment
- Platform+version: **iOS 15.3** 
- FLEX version: branch: Master
- Using Swift Package Manager
### Bug Report

Flex UI is broken:
![IMG_7037](https://user-images.githubusercontent.com/1849089/162800064-d7198835-28cc-45d3-a7f8-4f1df475ad10.jpg)

**Comment by quantumass** [comment]
I have the same problem

**Comment by tinder-tannerbennett** [comment]
I'm unable to reproduce this in Xcode 13.3.1 with the 15.4 simulator (there is no 15.3 simulator), can you provide a link or example project that does?

**Comment by NSExceptional** [comment]
I'm unable to reproduce this in Xcode 13.3.1 with the 15.4 simulator (there is no 15.3 simulator), can you provide a link or example project that does?

**Comment by HarveyDawn** [comment]
I have the same problem

**Comment by bing89757** [comment]
I have the same problem. Fix this problem by: call [[FLEXManager sharedManager] showExplorer] after [sell.window makeKeyAndVisible].

**Comment by liujyi** [comment]
> I have the same problem. Fix this problem by: call [[FLEXManager sharedManager] showExplorer] after [sell.window makeKeyAndVisible].

How can i trigger this bug，in order to test my new code，thanks
