### ISSUE TITLE
'tr1/unordered_map' file not found

### ISSUE THREAD

**Issue by jiasongs** [FLEXTool/FLEX#599]
### Environment
- Platform+version: iOS 15
- FLEX version: 4.7.0

### Bug Report
'tr1/unordered_map' file not found
<img width="1531" alt="图片" src="https://user-images.githubusercontent.com/22904757/166857288-91db1a2a-27f0-4b98-8a47-3efcca85b61f.png">

`spec.xcconfig` should be changed to `spec.pod_target_xcconfig`
<img width="402" alt="图片" src="https://user-images.githubusercontent.com/22904757/166857363-e04b609e-68d6-4b47-bc99-aad492c670a1.png">

**Comment by NSExceptional** [comment]
Fixed by #626
