### ISSUE TITLE
BigBoss binary needs updating from 4.4.0

### ISSUE THREAD

**Issue by badger200** [FLEXTool/FLEX#605]
I have theos but FLEX doesn’t seem compilable without XCode, so I need a binary to update.

**Comment by NSExceptional** [comment]
Is it really still on BigBoss? I told Optimo to take it down. Or are you talking about my repo? I don't think I've updated it there either

**Comment by badger200** [comment]
It was when I last installed it in February. Regardless I need an updated binary somehow.

**Comment by NSExceptional** [comment]
I forgot to reply, but it's on _my_ repo, not bigboss. `nscake.github.io`

**Comment by badger200** [comment]
I just got a v5.5(?) update on BigBoss! Yay!
