### ISSUE TITLE
Upgraded to 4.7.0, my previous c language like  ‘float _data_width = {};’ compiled with the following error

### ISSUE THREAD

**Issue by jinliyuelong** [FLEXTool/FLEX#613]
### Environment
- Platform+version: **iOS 14** 
- FLEX version: **4.7.0** 

### Bug Report

Here, you can provide a description of the bug. Some tips:

- Please do not paste an entire crash log. Upload the crash log to something like [ghostbin.co](https://ghostbin.co/) or another paste service. Alternatively, you can cut out the relevant stack trace and paste that inside a ` ```code block``` `
- If the bug is more complex than "this button is broken" or a crash, consider including a sample project. For example, if your app's requests aren't showing up in the network history page.
- Providing steps to reproduce is always helpful!
- If you want to include a screenshot or GIF, consider modifying the default markdown for uploaded images to use this code to make the image smaller on desktop:
  ```
  <img width="50%" src=your-image-url >
  ```
<img width="1466" alt="image" src="https://user-images.githubusercontent.com/16810284/182818715-1d29ba8e-70f7-4571-b14d-16c20267199d.png">

<img width="1451" alt="image" src="https://user-images.githubusercontent.com/16810284/182818929-5507d15e-2292-4e93-8288-2ab495fc01a1.png">

This template is a suggestion. You may format your issue however you want, but generally you should at least include your iOS version and FLEX version.

**Comment by NSExceptional** [comment]
FLEX doesn't affect your own project's compile flags

**Comment by jinliyuelong** [comment]
But he does influence, I compile correctly with 4.6.1, 4.7.0 reports an error。
4.6.0 success as below。
<img width="465" alt="image" src="https://user-images.githubusercontent.com/16810284/182982680-03a0cb30-3c63-4313-89c0-e5ecb6a1ab55.png">


<img width="1484" alt="image" src="https://user-images.githubusercontent.com/16810284/182982545-8dc420db-79df-4bf6-b06f-3f29a8ab7fde.png">

**Comment by jinliyuelong** [comment]
I'm wondering if 4.7.1 has been updated with some compilation environment, or if upgrading some compilation environment has affected

**Comment by NSExceptional** [comment]
Hi, can you try using the version of FLEX from `master`? I think this was resolved recently. My apologies
