### ISSUE TITLE
When installed using SPM in a Package.swift it doesn't seem possible to build for release

### ISSUE THREAD

**Issue by ryanbooker** [FLEXTool/FLEX#614]
### Environment

- Platform+version: **iOS 15.5**
- FLEX version: **4.7.0**

### Bug Report

- I have followed the instructions to add FLEX to a Package.swift.
- Excluding FLEX.o in release makes it impossible to build for release, as the swift package will still try to link against FLEX.
- If I include FLEX.o it builds. But we obviously don't want to include it for release builds.

Has anyone encountered this before and have a work around?

Thanks in advance.

**Comment by NSExceptional** [comment]
I was able to create a sample project and exclude FLEX's package from the release build. It will still _build_ flex, but the resulting app has no trace of FLEX in it.

What error are you seeing exactly?

**Comment by ryanbooker** [comment]
I couldn't get it to build it would give an error that it couldn't link against the library. But after your comment, I removed everything and started again and now it builds just fine for Release. 🤷‍♂️ Thanks for looking into it. I'm not sure what the problem was, but clearly it was something it what we'd done. Thanks. 🙃
