### ISSUE TITLE
support new version consultation for iOS16

### ISSUE THREAD

**Issue by MyronX** [FLEXTool/FLEX#617]
Hi. I see the latest code has fixed the crash of getting statusBar on iOS16. Do you have any estimates when the new version will be released?

**Comment by NSExceptional** [comment]
I'll get to this ASAP, apologies

**Comment by icedice** [comment]
I was hoping to use be able to build master and use that but I'm seeing this:

```
A shell task (/usr/bin/xcrun xcodebuild -project /Users/toke.refstrup/git/ios/Carthage/Checkouts/FLEX/Example/FLEXample-SPM.xcodeproj CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES -list) failed with exit code 74:
2022-10-14 10:32:27.769 xcodebuild[80861:10972975] Writing error result bundle to /var/folders/kp/c82dqjjx7kq7wm13b_y776tw0000gq/T/ResultBundle_2022-14-10_10-32-0027.xcresult
xcodebuild: error: Could not resolve package dependencies:
  Failed to clone repository /Users/tanner/Repos/Reflex:
    fatal: repository '/Users/tanner/Repos/Reflex' does not exist
```

**Comment by Saafo** [comment]
[5.22.10](https://github.com/FLEXTool/FLEX/releases/tag/5.22.10) had been released.

**Comment by NSExceptional** [comment]
Fixed @malhagi, sorry about that

**Comment by z-abhi** [comment]
Can you release a new tag? In v 5.22.10, it's still have local URL.

**Comment by z-abhi** [comment]
@NSExceptional 
Can you release a new tag? In v 5.22.10, it's still have local URL.
