### ISSUE TITLE
LICENSE, strongify, Headers, FLEXWindow error

### ISSUE THREAD

**Issue by Weever** [FLEXTool/FLEX#624]
## Environment
- Platform+version: **iOS 13.2.3** 
- FLEX version: **4.7.0** 

## Bug Report

I Add source code file to my project, not the pod or .framework or .a

### Error 1
Multiple commands produce 'xxx/Demo.app/LICENSE'
```
Classes/GlobalStateExplorers/DatabaseBrowser/LICENSE
Classes/Network/PonyDebugger/LICENSE'
```
I remove all LICENSE can build success

### Error 2
`strongify` and `weakify` error
I have other define name strongify and weakify, the name is same FLEXMacros.h strongify and weakify
I change name is `flex_strongify` and `flex_weakify`

### Error 3
Classes/Headers is link, Xcode build error not found class

### Other
FLEXWindow is keyWindow, then my keyWindow is not the first one.
```
FLEXExplorerViewController
- (void)presentViewController:(UIViewController *)toPresent
                               animated:(BOOL)animated
                             completion:(void (^)(void))completion {
    // Make our window key to correctly handle input.
    [self.view.window makeKeyWindow];

    ....
}
```

<FLEXWindow: 0x10c160300; baseClass = UIWindow; frame = (0 0; 375 667); gestureRecognizers = <NSArray: 0x2835140c0>; layer = <UIWindowLayer: 0x28282e1e0>>, isKeyWindow=1, windowLevel=1100.000000

UIApplication.sharedApplication.keyWindow

**Comment by NSExceptional** [comment]
I have `#ifndef strongify` guarding those macros; I think if you just reorder your imports (or do the same for your macros; guard them with `#ifndef XXX`) that can be avoided

> Classes/Headers is link, Xcode build error not found class

Are you using `master` in your podfile, or the last version directly? I know you put 4.7.0 but I'm just double checking

> FLEXWindow is keyWindow, then my keyWindow is not the first one.

Can you elaborate on your issue with this?

**Comment by Weever** [comment]
download `FLEX-4.7.0.zip`, and unzip `FLEX-4.7.0`, then copy `FLEX-4.7.0/Classes` into my project, change the name from `Classes` to `FLEX`,  and add to targets

> Classes/Headers is link, Xcode build error not found class

Is my problem, I change name

> Multiple commands produce 'xxx/Demo.app/LICENSE'

I only copy `Classes`, more Info.plist and LICENSE, I should be remove 


> I have other define name strongify and weakify

This macros is define other lib, I suggest maybe flex can rename is very nice ^_^

> FLEXWindow is keyWindow, then my keyWindow is not the first one.

That is very strange, in my project, when I tap FLEX menu, and tap done, I NSLog the keyWindow is FLEXWindow. I create new project it never happen

**Comment by NSExceptional** [comment]
> This macros is define other lib, I suggest maybe flex can rename is very nice ^_^

Which library is it, if you don't mind me asking? Is it libextobjc? Instead of polluting the global namespace with duplicate macros I would like to try to get them to guard their definition the same way I am, so that it doesn't matter what order the imports are in :)

> That is very strange, in my project, when I tap FLEX menu, and tap done, I NSLog the keyWindow is FLEXWindow

This is expected behavior I think; if you want to access your app's window, you should access the `window` property on your app delegate, or grab the window from the scene delegate if you're using the UIScene APIs
