### ISSUE TITLE
Apollo v1.14 crashes when network monitoring is enabled

### ISSUE THREAD

**Issue by IntriguingTiles** [FLEXTool/FLEX#625]
### Environment
- Platform+version: **iOS 14.3**
- libFLEX version: **4.7.0~b4**
- FLEXing version: **1.3.1**

### Bug Report
Enabling network monitoring immediately causes Apollo to crash and it will continue to crash on launch until network debugging is manually disabled.

This doesn't happen on previous versions of Apollo.

[Crash log.](https://pastebin.com/qctKA2B4)

**Comment by NSExceptional** [comment]
Looks like something in Apollo is doing the crashing. You'll have to reach out to him via email or on Twitter about it. He will probably not be too happy about it; he isn't fond of jailbreakers coming to him with crash logs :/
