### ISSUE TITLE
Reddit v2022.34.0 crashs

### ISSUE THREAD

**Issue by objc-class** [FLEXTool/FLEX#627]
### Environment
- Platform+version: **iOS 14.3**
- FLEX version: **4.7.0**

### Bug Report

Clicking on the views button when any view is selected will crash
Reason: Invalid parameter not satisfying: depthsForViews.count == allViews.count
Viewing 💩 Neap Objects also crashes

**Comment by brendonjkding** [comment]
Did some shallow research and found that Reddit implement -[PagedTab.SegmentItem hash].
So different PagedTab.SegmentItem object may return same hash, which causes depthsForViews.count < allViews.count.

**Comment by NSExceptional** [comment]
Is `PagedTab.SegmentItem` a UIView? So they're being added to `allViews` but only some are being kept because of the same hashes?

**Comment by brendonjkding** [comment]
Right, `PagedTab.SegmentItem` is kind of UIView. There are 9 `PagedTab.SegmentItem` on the home page, and all of them are in allViews but only 3 of them are kept in depthsForViews.
