### ISSUE TITLE
FLEX 5 (well, 5.22.10) public header files missing

### ISSUE THREAD

**Issue by apps4everyone** [FLEXTool/FLEX#636]
With the new version 5.22.10 there are some header file not public:

FLEXMetadataExtras.h
FLEXSwiftInternal.h
NSDateFormatter+FLEX.h

those have to be moved to public to be able to use them for example in XCFramework.

thx Stefan

**Comment by apps4everyone** [comment]
<img width="1705" alt="Screenshot 2022-10-21 at 17 36 28" src="https://user-images.githubusercontent.com/1915802/197246157-624f9d4b-5877-4750-b762-e51fdbf1e20b.png">

**Comment by NSExceptional** [comment]
Those are all private header files. Are you saying you're unable to compile the project? Or just unable to use them?

**Comment by apps4everyone** [comment]
they are private in the project, but if you generate a XCFramework they are not found outside of the target.

see FLEXObjcInternal is also in Public... FLEXSwiftInternal for example isn't...

<img width="2560" alt="Screenshot 2022-10-21 at 19 06 14" src="https://user-images.githubusercontent.com/1915802/197261013-3de13820-0bb3-4cb3-a662-64d7bd471bc2.png">

**Comment by apps4everyone** [comment]
FLEX-Runtime.h can't find them, they are imported there...

**Comment by apps4everyone** [comment]
all imports in public FLEX-Runtime.h also has to be in public.

**Comment by NSExceptional** [comment]
Thanks for reporting this! I didn't know anyone used the xcodeproj like this

**Comment by apps4everyone** [comment]
It's used when generating a XCFramework like described here:
https://github.com/FLEXTool/FLEX/pull/551

**Comment by apps4everyone** [comment]
we use the XCFramework instead of SPM to reduce recompilation (15-20 seconds) on every PR build

**Comment by mgray88** [comment]
Why was this closed? It doesn't seem to be fixed :(

**Comment by mgray88** [comment]
Got it working!

For anyone else still experience this issue:
If you are using Cocoapods with `modular_headers`, do a `pod update --clean-install FLEX` then clean & build the project
