### ISSUE TITLE
Use the attribute objc_direct to hide methods from categories.

### ISSUE THREAD

**Issue by Ram4096** [FLEXTool/FLEX#648]
Is it possible to implement the attribute objc_direct to convert methods to direct C calls in order to prevents apps to detect if there are methods from third-party dylibs in NSObject and more?

**Comment by NSExceptional** [comment]
Yes, but what does that have to do with FLEX?

**Comment by NeHyci** [comment]
> Is it possible to implement the attribute objc_direct to convert methods to direct C calls in order to prevents apps to detect if there are methods from third-party dylibs in NSObject and more?

I think this is useless because App only needs to detect tweak injection and no App seems to detect this.

**Comment by NSExceptional** [comment]
Some do, some don't. Snapchat will only ban you if you add methods to or swizzle methods on specific classes, so this isn't a bad idea!
