### ISSUE TITLE
not hook websocket use SocketRocket 

### ISSUE THREAD

**Issue by iPermanent** [FLEXTool/FLEX#650]
### Environment
- Platform+version: iOS 16.3 
- FLEX version:5.22.10 (with Cocoapods)

### Bug Report

Here I used the  SocketRocket to link my websocket server, however, when I open the pannel, the websocket data not show in the debug panel, however the rest http/https request is all well, [[FLEXManager sharedManager] setNetworkDebuggingEnabled:YES]; I added this in my appdelegate.m and didn't find any api to set the websocket separate, should I do something else?
 

Thanks

**Comment by NSExceptional** [comment]
Does SockerRocket use the Foundation websockets API or does it implement its own?

**Comment by iPermanent** [comment]
> 

https://github.com/facebookincubator/SocketRocket  Here is the code, as the code shows, without any webview inside so I think it's not use Foundation API, does FLEX only support Foudation APIs like some webview call ws?

**Comment by iPermanent** [comment]
OK, thanks
