### ISSUE TITLE
FLEXNetworkObserver.injectIntoAllNSURLThings Crashes

### ISSUE THREAD

**Issue by dp221125** [FLEXTool/FLEX#652]
### Environment
- Platform+version: **iOS 15.5** 
- FLEX version: **5.22.10** 

### Bug Report

- Steps
1. Import Charts 
2. Create a class that adopts ObservableObject. 
e.g
`public class Drawable: ObservableObject { }`
3.  Create a property wrapper like below
` @Published var method: InterpolationMethod`

InterpolationMethod is [Struct](https://developer.apple.com/documentation/charts/interpolationmethod?language=_8) used in Charts

Putting all of the above conditions together, we get the following code:

```
@available(iOS 16, *)
public class Drawable: ObservableObject {
    @Published var method: InterpolationMethod

    public init(
        method: InterpolationMethod = .catmullRom
    ) {
        self.method = method
    }
}
```

and then, When I build and run it crashes. (iOS 15.5)

of course, I wrote the code to run FLEX in the App

```
struct FLEX_ChartsApp: App {
    
    init() {
        FLEXManager.shared.showExplorer()
        FLEXManager.shared.isNetworkDebuggingEnabled = true
    }
}
```

- Crash Screen Shot
<img width="1511" alt="image" src="https://user-images.githubusercontent.com/10572119/218464194-0a20581f-6de8-47ad-b7e1-4b5dc676bd7e.png">

- Source Code
- I created the smallest project that can reproduce this issue. ([Github](https://github.com/dp221125/FLEXTool_Charts_Crash_Example))

**Comment by NSExceptional** [comment]
Looks like a crash in Swift itself; it doesn't crash on other versions. I'm not sure there's anything I can do
