### ISSUE TITLE
UI显示异常。该功能不可用。Flex version： 5.22.10

### ISSUE THREAD

**Issue by mancongiOS** [FLEXTool/FLEX#655]
iOS 14 ： UI display exception. The function is unavailable.
<img width=30% src=https://user-images.githubusercontent.com/16421332/218694215-dbf8ba08-5ae4-44fc-930a-3d81160ad651.PNG>

iOS 16 ： is OK。

**Comment by zhang2** [comment]
i have the same bug. my device is  IOS 15.4.1

**Comment by MichaelLau128** [comment]
I have the same issue, I am using a iphone 14 Pro max with ios 16.6.1.

**Comment by NSExceptional** [comment]
Can anyone link to an open source project or example project that demonstrates this issue? I'm unable to reproduce this. I will be closing it for now until someone can link some code that reproduces this bug

**Comment by jackqinling** [comment]
In my project I  put code [[FLEXManager sharedManager] showExplorer] at the first line of didFinishLaunchingWithOptions before setrootViercontroller reproduce the problem, when I put the code at the end line of didFinishLaunchingWithOptions function after set rootViewController, it works!
