### ISSUE TITLE
SPM setting to exclude FLEX from release builds?

### ISSUE THREAD

**Issue by sujinnaljin** [FLEXTool/FLEX#665]
As the way to exclude  FLEX from release builds, README describes as below.

> In Xcode, navigate to `Build Settings > Build Options > Excluded Source File Names`. For your Release configuration, set it to `FLEX*` like this to exclude all files with the FLEX prefix:

![image](https://user-images.githubusercontent.com/20410193/231328890-c030094b-5a53-4198-a729-2ab0b08a0e16.png)

But, the setting value in the image is `FLEX.o`.

What is the correct value? `FLEX*` or `FLEX.o`? Or does it not matter which one I choose?

**Comment by Orfeas** [comment]
@sujinnaljin I've been using `FLEX*` in my Projects and haven't had any issues with Apple submissions

**Comment by NSExceptional** [comment]
Closing with @Orfeas's answer
