### ISSUE TITLE
FLEXNetworkObserver(NSURLSessionTaskHelpers) method crash

### ISSUE THREAD

**Issue by wtdu** [FLEXTool/FLEX#669]
### Environment
- Platform+version: **iOS 13.6** 
- FLEX version: **9.9.9** 

### Bug Report

FLEXNetworkObserver(NSURLSessionTaskHelpers) call method which is "URLSession:task:didFinishDownloadingToURL:data:delegate:" lead to crash

![截屏2023-04-24 18 12 34](https://user-images.githubusercontent.com/42770407/233967684-b355b0e8-b9f6-422c-8bd6-7455ea85728a.png)

This template is a suggestion. You may format your issue however you want, but generally you should at least include your iOS version and FLEX version.

**Comment by NSExceptional** [comment]
Your device ran out of memory
