### ISSUE TITLE
Apple App Rejection due to _setWidth: method name

### ISSUE THREAD

**Issue by richimf** [FLEXTool/FLEX#671]
Apple is rejecting apps using this Library due to in its code it´s contained a function named ´_setWidth:´ and this matches with the Apple's APIs.

![unnamed](https://user-images.githubusercontent.com/6757869/236470918-dafbeb9d-2d0b-46da-bbe1-65eef684260c.png)

**Comment by NSExceptional** [comment]
Sorry but avoiding these errors is an anti-goal for FLEX. Probably shouldn't include FLEX in TestFlight builds either. If someone else needs it that bad there are other ways to distribute debug build apps to them
