### ISSUE TITLE
Purple warning in FLEXNetworkObserver.m

### ISSUE THREAD

**Issue by ingopaulsen** [FLEXTool/FLEX#681]
### Environment
- Platform+version: **Xcode 15.0+iOS 15** 
- FLEX version: **5.22.10 (current master)**

### Purple warning

I got this warning in FLEXNetworkObserver.m:

<img width="939" alt="FLEX warnings" src="https://github.com/FLEXTool/FLEX/assets/203617/0d7d69e4-16ff-498d-8c98-1dda13c20ee3">

**Comment by NSExceptional** [comment]
That is a bug within the app you're using, not within FLEX itself
