### ISSUE TITLE
Xcode yellow warnings in several files

### ISSUE THREAD

**Issue by ingopaulsen** [FLEXTool/FLEX#682]
### Environment
- Platform+version: **Xcode 15.0+iOS 12** 
- FLEX version: **5.22.10 (current master)**

### Xcode warnings

Unfortunately, I get the following warnings when I set iOS target to at least iOS 12.0 when I navigate to report navigator local:

- 'archivedDataWithRootObject:' is deprecated: first deprecated in iOS 12.0 - Use +archivedDataWithRootObject:requiringSecureCoding:error instead:
- 'asl_get' is deprecated: first deprecated in iOS 10.0 - os_log(3) has replaced asl(3)
- 'asl_next' is deprecated: first deprecated in iOS 10.0 - os_log(3) has replaced asl(3)
- 'asl_new' is deprecated: first deprecated in iOS 10.0 - os_log(3) has replaced asl(3)
- 'asl_release' is deprecated: first deprecated in iOS 10.0 - os_log(3) has replaced asl(3)
- 'asl_search' is deprecated: first deprecated in iOS 10.0 - os_log(3) has replaced asl(3)
- 'asl_set_query' is deprecated: first deprecated in iOS 10.0 - os_log(3) has replaced asl(3)
- @available does not protect availability here; use if (@available) instead
- 'dimsBackgroundDuringPresentation' is deprecated: first deprecated in iOS 12.0
- 'openURL:' is deprecated: first deprecated in iOS 10.0
- 'properties' is deprecated: first deprecated in iOS 10.0 - Use the more specific accessors below
- 'unarchiveObjectWithData:' is deprecated: first deprecated in iOS 12.0 - Use +unarchivedObjectOfClass:fromData:error instead

Affected files are: `FLEXUIAppShortcuts.m`, `FLEXTableViewController.m`, `FLEXSystemLogMessage.m`, `FLEXRuntimeExporter.m`, `FLEXProtocol.m`, `FLEXNetworkMITMViewController.m`, `FLEXKeychainQuery.m`, `FLEXFileBrowserController.m`, `FLEXExplorerViewController.m`, and `FLEXASLLogController.m`

**Comment by NSExceptional** [comment]
This project still supports iOS 9 and uses many APIs that were deprecated without replacement. It is not recommended that you change the deployment target to iOS 12.

That said, I have fixed some of the warnings by gating them with `if (@available(...))` statements as needed.
