### ISSUE TITLE
Support for Privacy Manifest

### ISSUE THREAD

**Issue by lambda123254** [FLEXTool/FLEX#686]
<img width="1657" alt="image" src="https://github.com/FLEXTool/FLEX/assets/103159356/8753de7b-64bf-4132-8874-d5f7e399407f">
UserDefaults is one of the function which require privacy manifest embedded in the library, this library use UserDefaults for I don't know I can't study all of your code lol, may be it'd be nice to see more details about this.

I'm still learning as well, so I might be wrong about this suggestion :/

**Comment by NSExceptional** [comment]
Hi,

Does it work locally without one? If it does, there is no need to add one. You shouldn't include FLEX in app store builds after all.

**Comment by lambda123254** [comment]
Oh yea, you're right, thanks for the respond

**Comment by lamdaniel** [comment]
I've checked and believe Flex uses:
NSFileCreationDate
fileModificationDate
NSUserDefaults

I assume privacy manifest is not required as we exclude it from release builds. Can anyone confirm?

**Comment by NSExceptional** [comment]
> I assume privacy manifest is not required as we exclude it from release builds.
Closing this for now based on this info. Let me know if that changes.
