### ISSUE TITLE
The folder “patches.plist” does not exist.

### ISSUE THREAD

**Issue by Brysonmhughes** [FLEXTool/FLEX#697]
### Environment
- Platform+version: **iOS 17.4.1** 
- FLEX version: **3 beta** 
<!--- FLEXing / libFLEX users: please include FLEXing and libFLEX versions separately --

**Comment by NSExceptional** [comment]
I need more information than this, I have no idea what this is about, sounds like it's an issue with something else

**Comment by SnoopyTools** [comment]
> ### Environment
> * Platform+version: **iOS 17.4.1**
> * FLEX version: **3 beta**
This is FLEXTOOL repo not "FLEX 3" they are 2 separate programs  also "FLEX 3" needs to be jailbroken to use and 17.5.1 cannot be jailbroken
